name: rtmidi_dart
description: Dart FFI bindings for RtMidi (cross-platform MIDI I/O library).
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  ffigen: ^12.0.0
  flutter_lints: ^6.0.0

ffigen:
  name: RtMidiFFI
  description: Generated bindings for RtMidi
  output: lib/src/bindings.dart
  headers:
    entry-points:
      - /usr/include/rtmidi/rtmidi_c.h
  llvm-path:
    - /usr/lib/llvm-18